GET http://localhost:3000/user-api/get-users

###
POST http://localhost:3000/user-api/add-user
Content-Type: application/json

{
    "id": 11,
    "name": "Batman",
    "username": "batman7",
    "email": "batman@gotham.city"
}


###
PUT http://localhost:3000/user-api/update-user/1
Content-Type: application/json

{
    "username": "batman_7"
}

###
DELETE http://localhost:3000/user-api/delete-user/9
